export { default as Dashboard } from "./dashboard/Dashboard";
export { default as AboutUs } from "./aboutUs/AboutUs";
export { default as ContactUs } from "./contactUs/ContactUs";
export { default as Poster } from "./poster/Poster";
export { default as SearchPage } from "./searchPage/SearchPage";
export { default as Privacypolicy } from "./privacypolicy/Privacypolicy";
export { default as Terms } from "./terms/Terms";
export { default as TempleteDetail } from "./templeteDetail/TempleteDetail";
export { default as BillingAddress } from "./billingAddress/billingAdress";
